using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SchoolAppointmentApp.Entities;

namespace SchoolAppointmentApp.Data.Configuration;

public class TeacherConfiguration : IEntityTypeConfiguration<Teacher>
{
    public void Configure(EntityTypeBuilder<Teacher> builder)
    {
        builder.HasKey(t => t.TeacherId);

        // Fast search
        builder.HasIndex(t => t.TeacherId);

        // TeacherId is required, cant be exceeding 10 char and it should not be AutoGenerated when inserted row.
        builder.Property(t => t.TeacherId)
                .IsRequired()
                .HasMaxLength(10)
                .ValueGeneratedNever();

        // Default to 0 if null
        builder.Property(t => t.Points)
                .HasDefaultValue(0);

        // One to one relation with user, FK is Teacher.UserId and 
        // when User is deleted the Teacher record delete as well 
        builder.HasOne(t => t.User)
                .WithOne(u => u.Teacher)
                .HasForeignKey<Teacher>(t => t.UserId)
                .OnDelete(DeleteBehavior.Cascade);

        builder.Property(t => t.UserId)
                .IsRequired();

    }
}