// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolAppointmentApp.Data;

#nullable disable

namespace SchoolAppointmentApp.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20260509062900_MainPostRelationIssues")]
    partial class MainPostRelationIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminLoginId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.HasIndex("AdminLoginId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AdminLoginId = "iwueowsakd62981sksai",
                            PasswordHash = "AQAAAAIAAYagAAAAEMRaGtjqdh0fBDTRhUT6cyIJME6FyreJVOKsdXOSOhJ6ifmqjbg1I/4i5TTGP66x9A=="
                        },
                        new
                        {
                            AdminId = 2,
                            AdminLoginId = "84u232fhfehw889d0ufd",
                            PasswordHash = "AQAAAAIAAYagAAAAEMRaGtjqdh0fBDTRhUT6cyIJME6FyreJVOKsdXOSOhJ6ifmqjbg1I/4i5TTGP66x9A=="
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Block", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitiatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("RequestId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("ReceiverId", "InitiatorId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Ordered")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalCost")
                        .HasColumnType("integer");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("\"Ordered\" = false");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.FriendRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InitiatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("RequestId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("StatusId");

                    b.HasIndex("ReceiverId", "InitiatorId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.FriendRequestStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("FriendRequestPossibleStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("FriendRequestStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            FriendRequestPossibleStatus = "Pending"
                        },
                        new
                        {
                            StatusId = 2,
                            FriendRequestPossibleStatus = "Denied"
                        },
                        new
                        {
                            StatusId = 3,
                            FriendRequestPossibleStatus = "Accepted"
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.MainPost", b =>
                {
                    b.Property<int>("MainPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MainPostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumOfThumbsUp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.HasKey("MainPostId");

                    b.HasIndex("StudentId");

                    b.ToTable("MainPosts");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("AudioMessageRoot")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ImageMessageRoot")
                        .HasColumnType("text");

                    b.Property<DateTime>("MessageDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId", "ReceiverId");

                    b.ToTable("Messages", t =>
                        {
                            t.HasCheckConstraint("CheckMessageHasExactlyOneTypeOfContent", "(\r\n                (CASE WHEN \"Content\" IS NOT NULL AND length(trim(\"Content\")) > 0 THEN 1 ELSE 0 END) +\r\n                (CASE WHEN \"AudioMessageRoot\" IS NOT NULL THEN 1 ELSE 0 END) +\r\n                (CASE WHEN \"ImageMessageRoot\" IS NOT NULL THEN 1 ELSE 0 END)\r\n            ) = 1");
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCost")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.OrderItemStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("OrderItemStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Status = "pending"
                        },
                        new
                        {
                            StatusId = 2,
                            Status = "received"
                        },
                        new
                        {
                            StatusId = 3,
                            Status = "cancelled"
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Status = "pending"
                        },
                        new
                        {
                            StatusId = 2,
                            Status = "cancelled"
                        },
                        new
                        {
                            StatusId = 3,
                            Status = "received"
                        },
                        new
                        {
                            StatusId = 4,
                            Status = "mix"
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointCost")
                        .HasColumnType("integer");

                    b.Property<string>("ProductImageRoot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AvailableQuantity = 5,
                            Description = "Just a item",
                            PointCost = 1,
                            ProductImageRoot = "../Example1",
                            ProductName = "item"
                        },
                        new
                        {
                            ProductId = 2,
                            AvailableQuantity = 30,
                            Description = "Just a snack",
                            PointCost = 2,
                            ProductImageRoot = "../Example2",
                            ProductName = "snack"
                        },
                        new
                        {
                            ProductId = 3,
                            AvailableQuantity = 10,
                            Description = "Just a tool ",
                            PointCost = 3,
                            ProductImageRoot = "../Example3",
                            ProductName = "tool"
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Reply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReplyId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MainPostId")
                        .HasColumnType("integer");

                    b.Property<int>("NumOfThumbsUp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReplyId");

                    b.HasIndex("MainPostId");

                    b.HasIndex("UserId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Report", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<int>("InitiatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportedContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("ReceiverId", "InitiatorId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.SchoolClass", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClassId");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.ToTable("SchoolClasses");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "電通一甲"
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "電通二甲"
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "電通三甲"
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.SchoolPrincipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SchoolPrincipal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEMRaGtjqdh0fBDTRhUT6cyIJME6FyreJVOKsdXOSOhJ6ifmqjbg1I/4i5TTGP66x9A==",
                            PrincipalId = "L123456"
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TodaysEarning")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TeacherId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.ThumbsUpInfo", b =>
                {
                    b.Property<int>("ThumbsUpInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThumbsUpInfoId"));

                    b.Property<int?>("MainPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplyId")
                        .HasColumnType("integer");

                    b.Property<bool>("Thumbed")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ThumbsUpInfoId");

                    b.HasIndex("UserId");

                    b.HasIndex("MainPostId", "UserId");

                    b.HasIndex("ReplyId", "UserId");

                    b.ToTable("ThumbsUpInfos", t =>
                        {
                            t.HasCheckConstraint("CK_ReplyIdAndPostIdCoExist", "(\"MainPostId\" IS NULL AND \"ReplyId\" IS NOT NULL)OR (\"ReplyId\" IS NULL AND \"MainPostId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("Terminate")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Block", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiator");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Cart", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.CartItem", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.Cart", "Cart")
                        .WithMany("CartProductList")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.FriendRequest", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.FriendRequestStatus", "FriendRequestStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendRequestStatus");

                    b.Navigation("Initiator");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.MainPost", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Message", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Order", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.OrderItem", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.OrderItemStatus", "OrderItemStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderItemStatus");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Reply", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.MainPost", "MainPost")
                        .WithMany("Replies")
                        .HasForeignKey("MainPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Report", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiator");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Student", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.SchoolClass", "SchoolClass")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolAppointmentApp.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SchoolAppointmentApp.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolClass");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Teacher", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("SchoolAppointmentApp.Entities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.ThumbsUpInfo", b =>
                {
                    b.HasOne("SchoolAppointmentApp.Entities.MainPost", "MainPost")
                        .WithMany("ThumbsUpInfos")
                        .HasForeignKey("MainPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolAppointmentApp.Entities.Reply", "Reply")
                        .WithMany("ThumbsUpInfos")
                        .HasForeignKey("ReplyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SchoolAppointmentApp.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainPost");

                    b.Navigation("Reply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Cart", b =>
                {
                    b.Navigation("CartProductList");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.MainPost", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("ThumbsUpInfos");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.Reply", b =>
                {
                    b.Navigation("ThumbsUpInfos");
                });

            modelBuilder.Entity("SchoolAppointmentApp.Entities.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
